name: Chester
main: Chester\Main
version: "1.0.0"
author: RTG
api: [1.0.0, 2.0.0, 3.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7]
load: STARTUP
commands:
 c:
  permission: chester.command
  description: Main command
  usage: /c <add|remove|reload|reset>
permissions:
 chester.*:
  default: op
  description: Main permission
  children:
   chester.command.*:
    default: op
    description: use commands
